rm json/s3staticpol.json 
rm json/sqspol.json
rm json/s3imagespol.json
rm json/s3notif.json
rm json/s3archivespol.json
rm lambda/zipper.py
rm lambda/manager.py
rm lambda/zipper.zip
rm lambda/manager.zip
rm .elasticbeanstalk/config.yml
rmdir .elasticbeanstalk
rm helloworld/settings.py