branch-defaults:
  default:
    environment: flask-env-jer
    group_suffix: null
  master:
    environment: flask-env-jer
    group_suffix: null
global:
  application_name: django-tutorial
  branch: null
  default_ec2_keyname: ingi2145
  default_platform: python2.7
  default_region: us-west-2
  profile: null
  repository: null
  sc: null
